return {
  {
    "AstroNvim/astrocommunity",
  },
  { import = "colorscheme.catppuccin" },

  -- { import = "comment.comment" },
  -- { import = "completion.cmp-buffer" },
  -- { import = "astrocommunity.completion.cmp-calc" },
  { import = "astrocommunity.completion.cmp-cmdline" },
  -- { import = "astrocommunity.completion.cmp-emoji" },
  -- { import = "astrocommunity.completion.cmp-latex-symbols" },
  -- { import = "astrocommunity.completion.cmp-git" },
  -- { import = "astrocommunity.completion.cmp-nerdfont" },
  -- { import = "astrocommunity.completion.cmp-nvim-lua" },
  -- { import = "astrocommunity.completion.cmp-spell" },
  -- { import = "astrocommunity.completion.cmp-tmux" },
  -- { import = "astrocommunity.completion.cmp-under-comparator" },
  -- { import = "astrocommunity.completion.nvim-cmp-buffer-lines" },
  -- { import = "astrocommunity.completion.coq_nvim" },

  { import = "pack.lua" },
  { import = "pack.markdown" },
  { import = "pack.nginx" },
  { import = "astrocommunity.pack.python" },
  -- { import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.markdown-nvim" },
  { import = "astrocommunity.markdown-and-latex.peek-nvim" },
  -- { import = "astrocommunity.markdown-and-latex.vimtex" },
  { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
  { import = "recipes.vscode" },

  { import = "astrocommunity.utility.noice-nvim" },
  { import = "utility.vim-macos-ime" },
  { import = "programming-language-support.rest-nvim" },
  { import = "astrocommunity.editing-support.nvim-context-vt" },
  -- { import = "astrocommunity.editing-support.nvim-origami" },
  { import = "astrocommunity.editing-support.nvim-treesitter-context" },
  { import = "astrocommunity.editing-support.suda-vim" },
  -- { import = "astrocommunity.editing-support.text-case-nvim" },
  { import = "astrocommunity.editing-support.undotree" },
  { import = "editing-support.vim-doge" },
  { import = "astrocommunity.editing-support.vim-move" },
  -- { import = "astrocommunity.editing-support.vim-visual-multi" },
  { import = "astrocommunity.editing-support.wildfire-nvim" },
  -- { import = "astrocommunity.editing-support.yanky-nvim" },
  { import = "astrocommunity.file-explorer.oil-nvim" },
  -- { import = "astrocommunity.file-explorer.telescope-file-browser-nvim" },
  -- { import = "astrocommunity.git.blame-nvim" },
  { import = "git.git-blame-nvim" },
  -- { import = "astrocommunity.indent.indent-blankline-nvim" },
  { import = "astrocommunity.indent.indent-rainbowline" },
  { import = "astrocommunity.lsp.garbage-day-nvim" },
  { import = "astrocommunity.lsp.inc-rename-nvim" },
  -- { import = "astrocommunity.lsp.lsp-lens-nvim" },
  { import = "astrocommunity.lsp.lsplinks-nvim" },
  { import = "lsp.lspsaga-nvim" },
  { import = "astrocommunity.lsp.nvim-lint" }, --TODO:确认是否有用
  -- { import = "astrocommunity/lsp/nvim-lsp-file-operations" },
  { import = "astrocommunity/media/vim-wakatime" },
  { import = "astrocommunity/media/codesnap-nvim" },
  { import = "astrocommunity/motion/flash-nvim" },
}
